---
- name: Create New CloudBlockStore Volume
  hosts: cloudblockstore
  connection: local
  gather_facts: no
  #  vars_files:
  #  - ./secrets.yaml
  collections:
  - purestorage.flasharray
  
  tasks:
    - name: create a new volume
      purefa_volume:
        name: "{{ volname }}"
        size: "{{ size }}"
        fa_url: "{{ fa_url }}"
        api_token: "{{ pure_api_token }}"
        state: present
      register: new_volume

    - name: print volume_volume
      debug:
        var: new_volume
