---
- hosts: "{{ cloud_initiator }}"
  gather_facts: no
  vars:
    ansible_shell_type: powershell
  tasks:

    - name: Add Pure FlashArray as an MPIO vendor
      win_shell: New-MSDSMSupportedHw -VendorId PURE -ProductId FlashArray

    - name: Enable iSCSI support by Microsoft MPIO
      win_shell: Enable-MSDSMAutomaticClaim -BusType iSCSI

    - name: Set default MPIO path policy to Lowest Queue Depth
      win_shell: Set-MSDSMGlobalDefaultLoadBalancePolicy -Policy LQD

    - name: Create a new Target Portal connection between your Windows host and your Cloud Block Store instance
      win_shell: New-IscsiTargetPortal -TargetPortalAddress "{{ hostvars.cloudblockstore.iscsiportalct0ip.stdout }}"

    - name: Retrieve number of vcpu
      win_shell: $(Get-WmiObject Win32_ComputerSystem).numberoflogicalprocessors
      register: winserver_vcpu

      #    - debug:
      #        var: winserver_vcpu

    - set_fact:
        vcpu: "{{ winserver_vcpu.stdout | trim }}"
        cacheable: yes

    - name: "Print vcpu count from hostvars"
      debug:
        msg: "{{ hostvars[inventory_hostname]['vcpu'] }}"

    - name: create iSCSI sessions for initiator with 1 vcpu
      win_shell: |
              for ($i=1; $i -le 1; $i++){
              Get-IscsiTarget | Connect-IscsiTarget -InitiatorPortalAddress "{{ cloud_initiator }}" -IsMultipathEnabled $true -IsPersistent $true -TargetPortalAddress "{{ hostvars.cloudblockstore.iscsiportalct0ip.stdout }}"
              Get-IscsiTarget | Connect-IscsiTarget -InitiatorPortalAddress "{{ cloud_initiator }}" -IsMultipathEnabled $true -IsPersistent $true -TargetPortalAddress "{{ hostvars.cloudblockstore.iscsiportalct1ip.stdout }}"
              }
      when: hostvars[inventory_hostname]['vcpu']|int == 1

    - name: create iSCSI sessions for initiator with 2 vcpu
      win_shell: |
              for ($i=1; $i -le 1; $i++){
              Get-IscsiTarget | Connect-IscsiTarget -InitiatorPortalAddress "{{ cloud_initiator }}" -IsMultipathEnabled $true -IsPersistent $true -TargetPortalAddress "{{ hostvars.cloudblockstore.iscsiportalct0ip.stdout }}"
              Get-IscsiTarget | Connect-IscsiTarget -InitiatorPortalAddress "{{ cloud_initiator }}" -IsMultipathEnabled $true -IsPersistent $true -TargetPortalAddress "{{ hostvars.cloudblockstore.iscsiportalct1ip.stdout }}"
              }
      when: hostvars[inventory_hostname]['vcpu']|int == 2

    - name: create iSCSI sessions for initiator with 4 vcpu
      win_shell: |
              for ($i=1; $i -le 2; $i++){
              Get-IscsiTarget | Connect-IscsiTarget -InitiatorPortalAddress "{{ cloud_initiator }}" -IsMultipathEnabled $true -IsPersistent $true -TargetPortalAddress "{{ hostvars.cloudblockstore.iscsiportalct0ip.stdout }}"
              Get-IscsiTarget | Connect-IscsiTarget -InitiatorPortalAddress "{{ cloud_initiator }}" -IsMultipathEnabled $true -IsPersistent $true -TargetPortalAddress "{{ hostvars.cloudblockstore.iscsiportalct1ip.stdout }}"
              }
      when: hostvars[inventory_hostname]['vcpu']|int == 4

    - name: create iSCSI sessions for initiator with 8 vcpu
      win_shell: |
              for ($i=1; $i -le 4; $i++){
              Get-IscsiTarget | Connect-IscsiTarget -InitiatorPortalAddress "{{ cloud_initiator }}" -IsMultipathEnabled $true -IsPersistent $true -TargetPortalAddress "{{ hostvars.cloudblockstore.iscsiportalct0ip.stdout }}"
              Get-IscsiTarget | Connect-IscsiTarget -InitiatorPortalAddress "{{ cloud_initiator }}" -IsMultipathEnabled $true -IsPersistent $true -TargetPortalAddress "{{ hostvars.cloudblockstore.iscsiportalct1ip.stdout }}"
              }
      when: hostvars[inventory_hostname]['vcpu']|int == 8

    - name: create iSCSI sessions for initiator with 16 vcpu
      win_shell: |
              for ($i=1; $i -le 8; $i++){
              Get-IscsiTarget | Connect-IscsiTarget -InitiatorPortalAddress "{{ cloud_initiator }}" -IsMultipathEnabled $true -IsPersistent $true -TargetPortalAddress "{{ hostvars.cloudblockstore.iscsiportalct0ip.stdout }}"
              Get-IscsiTarget | Connect-IscsiTarget -InitiatorPortalAddress "{{ cloud_initiator }}" -IsMultipathEnabled $true -IsPersistent $true -TargetPortalAddress "{{ hostvars.cloudblockstore.iscsiportalct1ip.stdout }}"
              }
      when: hostvars[inventory_hostname]['vcpu']|int == 16

    - name: create iSCSI sessions for initiator with 32 vcpu
      win_shell: |
              for ($i=1; $i -le 16; $i++){
              Get-IscsiTarget | Connect-IscsiTarget -InitiatorPortalAddress "{{ cloud_initiator }}" -IsMultipathEnabled $true -IsPersistent $true -TargetPortalAddress "{{ hostvars.cloudblockstore.iscsiportalct0ip.stdout }}"
              Get-IscsiTarget | Connect-IscsiTarget -InitiatorPortalAddress "{{ cloud_initiator }}" -IsMultipathEnabled $true -IsPersistent $true -TargetPortalAddress "{{ hostvars.cloudblockstore.iscsiportalct1ip.stdout }}"
              }
      when: hostvars[inventory_hostname]['vcpu']|int == 32

    - name: create iSCSI sessions for initiator with 36 vcpu
      win_shell: |
              for ($i=1; $i -le 18; $i++){
              Get-IscsiTarget | Connect-IscsiTarget -InitiatorPortalAddress "{{ cloud_initiator }}" -IsMultipathEnabled $true -IsPersistent $true -TargetPortalAddress "{{ hostvars.cloudblockstore.iscsiportalct0ip.stdout }}"
              Get-IscsiTarget | Connect-IscsiTarget -InitiatorPortalAddress "{{ cloud_initiator }}" -IsMultipathEnabled $true -IsPersistent $true -TargetPortalAddress "{{ hostvars.cloudblockstore.iscsiportalct1ip.stdout }}"
              }
      when: hostvars[inventory_hostname]['vcpu']|int == 36

    - name: create iSCSI sessions for initiator with 40 vcpu
      win_shell: |
              for ($i=1; $i -le 20; $i++){
              Get-IscsiTarget | Connect-IscsiTarget -InitiatorPortalAddress "{{ cloud_initiator }}" -IsMultipathEnabled $true -IsPersistent $true -TargetPortalAddress "{{ hostvars.cloudblockstore.iscsiportalct0ip.stdout }}"
              Get-IscsiTarget | Connect-IscsiTarget -InitiatorPortalAddress "{{ cloud_initiator }}" -IsMultipathEnabled $true -IsPersistent $true -TargetPortalAddress "{{ hostvars.cloudblockstore.iscsiportalct1ip.stdout }}"
              }
      when: hostvars[inventory_hostname]['vcpu']|int == 40

    - name: create iSCSI sessions for initiator with 48 vcpu
      win_shell: |
              for ($i=1; $i -le 24; $i++){
              Get-IscsiTarget | Connect-IscsiTarget -InitiatorPortalAddress "{{ cloud_initiator }}" -IsMultipathEnabled $true -IsPersistent $true -TargetPortalAddress "{{ hostvars.cloudblockstore.iscsiportalct0ip.stdout }}"
              Get-IscsiTarget | Connect-IscsiTarget -InitiatorPortalAddress "{{ cloud_initiator }}" -IsMultipathEnabled $true -IsPersistent $true -TargetPortalAddress "{{ hostvars.cloudblockstore.iscsiportalct1ip.stdout }}"
              }
      when: hostvars[inventory_hostname]['vcpu']|int == 48

    - name: create iSCSI sessions for initiator with 64 vcpu
      win_shell: |
              for ($i=1; $i -le 32; $i++){
              Get-IscsiTarget | Connect-IscsiTarget -InitiatorPortalAddress "{{ cloud_initiator }}" -IsMultipathEnabled $true -IsPersistent $true -TargetPortalAddress "{{ hostvars.cloudblockstore.iscsiportalct0ip.stdout }}"
              Get-IscsiTarget | Connect-IscsiTarget -InitiatorPortalAddress "{{ cloud_initiator }}" -IsMultipathEnabled $true -IsPersistent $true -TargetPortalAddress "{{ hostvars.cloudblockstore.iscsiportalct1ip.stdout }}"
              }
      when: hostvars[inventory_hostname]['vcpu']|int >= 64

    - name: Set MPIO Timer Values
      win_shell: Set-MPIOSetting -NewPathRecoveryInterval 20 -CustomPathRecovery Enabled -NewPDORemovePeriod 30 -NewDiskTimeout 60 -NewPathVerificationState Enabled

      #    - name: Restart OS for MPIO Timer Values to Take Effect
      #      win_shell: Restart-Computer
